# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# [TEMPLATE] Compile library mrwebrtc.dll

parameters:
  buildAgent: ''
  buildPlatform: ''    # Win32|UWP
  buildArch: ''        # x86|x64|ARM|ARM64
  msbuildPlatform: ''  # Win32|x64|ARM|ARM64
  buildConfig: ''      # Debug|Release

jobs:

# Compile mrwebrtc.dll
- job: mrwebrtc_${{parameters.buildPlatform}}_${{parameters.buildArch}}_${{parameters.buildConfig}}
  displayName: 'mrwebrtc (${{parameters.buildPlatform}}-${{parameters.buildArch}}-${{parameters.buildConfig}})'
  timeoutInMinutes: 360
  pool:
    name: ${{parameters.buildAgent}}
    demands: msbuild
  variables:
  - group: MixedReality-WebRTC-ArtifactConfig
  - name: buildTriple
    value: ${{parameters.buildPlatform}}-${{parameters.buildArch}}-${{parameters.buildConfig}}
  # This is overwritten later if restoring PDBs
  - name: PackagesConfigFile
    value: '$(Build.SourcesDirectory)/tools/build/mrwebrtc/${{parameters.buildPlatform}}/packages.config'
  steps:
  - checkout: 'self'
    submodules: 'recursive'
    fetchDepth: '1'

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: 'Map script variables'
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)/tools/ci/mapVariables.ps1'
      arguments: '${{parameters.buildPlatform}} ${{parameters.buildArch}} ${{parameters.buildConfig}}'
    timeoutInMinutes: 5

  # Compute the PDB package variables
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - task: PowerShell@2
      displayName: 'Compute libwebrtc PDB package variables'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/tools/ci/computePdbPackageVars.ps1'
      env:
        # Read $(MRWebRTC_PdbPackageVersion) from pipeline variables
        WRITE_VERSION: 'false'
      timeoutInMinutes: 5

  # Download the PDBs for libwebrtc
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - task: UniversalPackages@0
      displayName: 'Download libwebrtc PDBs'
      inputs:
        command: download
        vstsFeed: $(MRWebRTC_PdbFeed)
        vstsFeedPackage: $(MRWebRTC_PdbPackageName)
        vstsPackageVersion: $(MRWebRTC_PdbPackageVersion)
        downloadDirectory: '$(Build.SourcesDirectory)\_pdbs'
      timeoutInMinutes: 10

  # Move PDBs back into their original location for the linker to find them
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - task: PowerShell@2
      displayName: 'Move libwebrtc PDBs back in place'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/tools/ci/copyPdbsForBuilding.ps1'
        arguments: '-BuildConfig ${{parameters.buildConfig}} -BuildPlatform ${{parameters.buildPlatform}} -SourcePath "$(Build.SourcesDirectory)/_pdbs" -OutputPath "bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}"'
      timeoutInMinutes: 10

  # Use NuGet 5.2.0
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.2.0'
    inputs:
      versionSpec: 5.2.0
    timeoutInMinutes: 5

  # Generate custom packages.config to restore only the necessary packages for the current build triple.
  # This helps both with decreasing restore time and with minimizing disk space to avoid the 10GB limit.
  # This task sets $(PackagesConfigFile) to the filename of the generated 'packages.config' file.
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - task: PowerShell@2
      displayName: 'Generate packages.config for build triple'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/tools/ci/generateCppPackagesConfig.ps1'
        arguments: '-BuildConfig ${{parameters.buildConfig}} -BuildPlatform ${{parameters.buildPlatform}} -BuildArch ${{parameters.buildArch}} -InputFile "$(Build.SourcesDirectory)/tools/build/mrwebrtc/${{parameters.buildPlatform}}/packages.config" -OutputFile "bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}/packages.config"'
      timeoutInMinutes: 5

  # Restore the NuGet packages containing the input dependencies (non-PDB case)
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'NuGet restore mrwebrtc'
    inputs:
      command: 'restore'
      restoreSolution: '$(PackagesConfigFile)'
      restoreDirectory: '$(Build.SourcesDirectory)/packages'
      includeNuGetOrg: true
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGetConfigPath)'
    timeoutInMinutes: 30

  # Ensure that Python 2.7.16+ is the default; the Google scripts don't work with Python 3.x
  - task: UsePythonVersion@0
    displayName: 'Use Python 2.7.16+ x64 for Google GN'
    inputs:
      versionSpec: '>=2.7.16 <2.8.0'
    timeoutInMinutes: 5

  # Map build* variables to script* ones
  - task: PowerShell@2
    displayName: 'Map script variables'
    inputs:
      targetType: 'filePath'
      filePath: 'tools/ci/mapVariables.ps1'
      arguments: '${{parameters.buildPlatform}} ${{parameters.buildArch}} ${{parameters.buildConfig}}'
    timeoutInMinutes: 5

  # Prepare the environment with the setup script from Google
  - task: PythonScript@0
    displayName: 'Prepare WebRTC env'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'external/webrtc-uwp-sdk/scripts/run.py'
      arguments: '-a prepare -p $(scriptPlatform) --cpus $(scriptArch) -c $(scriptConfig)'
    timeoutInMinutes: 10

  # Clean-up unused files
  - script: |
      del /F /S /Q "depot_tools/external_bin/gsutil"
      del /F /S /Q "chromium/third_party/protobuf/java"
      del /F /S /Q "chromium/tools/android"
      del /F /S /Q "chromium/tools/code_coverage"
    workingDirectory: 'external/webrtc-uwp-sdk/webrtc/xplatform'
    displayName: 'Clean-up unused files'

  # Generate custom .vcxproj to import only the necessary packages for the current build triple
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - task: PowerShell@2
      displayName: 'Modify .vcxproj for build triple'
      inputs:
        targetType: filePath
        filePath: tools/ci/modifyCppProject.ps1
        arguments: '-BuildConfig ${{parameters.buildConfig}} -BuildPlatform ${{parameters.buildPlatform}} -BuildArch ${{parameters.buildArch}} -ProjectFile "tools/build/mrwebrtc/${{parameters.buildPlatform}}/mrwebrtc-${{parameters.buildPlatform}}.vcxproj"'

  # Run component detection
  - ${{ if eq(variables['MRWebRTC_RunComponentDetection'], 'true') }}:
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      timeoutInMinutes: 15

  # Build mrwebrtc.dll
  - task: MSBuild@1
    displayName: 'Build mrwebrtc ($(buildTriple))'
    inputs:
      solution: 'tools/build/mrwebrtc/${{parameters.buildPlatform}}/mrwebrtc-${{parameters.buildPlatform}}.vcxproj'
      msbuildVersion: 15.0
      msbuildArchitecture: x64
      platform: '${{parameters.msbuildPlatform}}'
      configuration: '${{parameters.buildConfig}}'
    timeoutInMinutes: 20

  # Publish mrwebrtc.dll and associated files (PDB, ...)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish mrwebrtc ($(buildTriple))'
    inputs:
      artifactName: 'mrwebrtc_$(buildTriple)'
      targetPath: 'bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}'

  # Delete PDBs to save disk space, otherwise the NuGet download below fails in Debug
  - ${{ if eq(variables['MRWebRTC_RestorePDBs'], 'true') }}:
    - powershell: |
        Remove-Item "bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}/*" -Force -Include "*.pdb" -Exclude "Microsoft.MixedReality.WebRTC.*","NativeLib.*","NativeTests.*"
      displayName: 'Delete PDBs after linking webrtc.lib'

  # Restore the NuGet packages for the mrwebrtc tests
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2  # NuGetCommand@2
    displayName: 'NuGet restore tests'
    inputs:
      command: restore
      restoreSolution: '$(Build.SourcesDirectory)/tools/build/mrwebrtc/win32/tests/packages.config'
      restoreDirectory: '$(Build.SourcesDirectory)/packages'
      includeNuGetOrg: true
      feedsToUse: 'config'
      nugetConfigPath: '$(NuGetConfigPath)'
    timeoutInMinutes: 10

  # Build the mrwebrtc tests
  - task: MSBuild@1
    condition: eq('${{parameters.buildPlatform}}', 'Win32')
    displayName: 'Build tests ($(buildTriple))'
    inputs:
      solution: '$(Build.SourcesDirectory)/tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj'
      msbuildVersion: '15.0'
      msbuildArchitecture: 'x64'
      platform: '${{parameters.msbuildPlatform}}'
      configuration: '${{parameters.buildConfig}}'
      msbuildArguments: '/p:DisableDeviceTests=1' # Disable tests requiring a webcam or microphone
    timeoutInMinutes: 15

  # Run mrwebrtc test
  - task: VSTest@2
    condition: eq('${{parameters.buildPlatform}}', 'Win32')
    displayName: 'Run tests ($(buildTriple))'
    inputs:
      testAssemblyVer2: 'mrwebrtc-win32-tests.exe'
      searchFolder: '$(Build.SourcesDirectory)/bin/${{parameters.buildPlatform}}/${{parameters.buildArch}}/${{parameters.buildConfig}}'
      pathtoCustomTestAdapters: '$(Build.SourcesDirectory)/packages/GoogleTestAdapter.0.16.1/build/_common'
    timeoutInMinutes: 30
